package com.example.joney.demo20.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.joney.demo20.entity.Dataset;

import com.example.joney.demo20.entity.DatasetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig datasetDaoConfig;

    private final DatasetDao datasetDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        datasetDaoConfig = daoConfigMap.get(DatasetDao.class).clone();
        datasetDaoConfig.initIdentityScope(type);

        datasetDao = new DatasetDao(datasetDaoConfig, this);

        registerDao(Dataset.class, datasetDao);
    }
    
    public void clear() {
        datasetDaoConfig.clearIdentityScope();
    }

    public DatasetDao getDatasetDao() {
        return datasetDao;
    }

}
